config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :user, only: %i[show edit update]

  resources :articles do
    resources :comments, only: %i[create destroy update edit]
  end

  get "/like_user/:id", to: "user#like"
  get "/like_article/:id", to: "articles#like"
  get "/like_comment/:article_id/:comment_id", to: "comments#like"
  root to: "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user, optional: true
  has_rich_text :content
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :article, optional: true
  has_rich_text :content
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :avatar
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :not_found
  before_action :get_current_user_desc

  private

  def get_current_user_desc
    if user_signed_in?
      @current_user = User.find_by id: current_user.id
    end
  end

  def not_found
    render file: "public/404.html", status: :not_found, layout: false
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: %i[show edit update destroy]
  def index
    if !params[:tag].nil? && params[:tag] == "AH"
      @articles = Article.where(category: "AH")
    elsif !params[:tag].nil? && params[:tag] == "HS"
      @articles = Article.where(category: "HS")
    elsif !params[:tag].nil? && params[:tag] == "AN"
      @articles = Article.where(category: "AN")
    elsif !params[:tag].nil? && params[:tag] == "FA" && !current_user.nil?
      @articles = Article.where :liked_by.include? current_user.id.to_s + ","
    else
      @articles = Article.all
    end

    if !params[:time].nil? && params[:time] == "D"
      @articles = @articles.where(:created_at => Time.now.prev_day...Time.now).order(created_at: :desc)
    elsif !params[:time].nil? && params[:time] == "W"
      @articles = @articles.where(:created_at => Time.now.prev_day(7)...Time.now).order(created_at: :desc)
    elsif !params[:time].nil? && params[:time] == "M"
      @articles = @articles.where(:created_at => Time.now.prev_month...Time.now).order(created_at: :desc)
    elsif !params[:time].nil? && params[:time] == "Y"
      @articles = @articles.where(:created_at => Time.now.prev_year...Time.now).order(created_at: :desc)
    else
      @articles = @articles.order(created_at: :desc)
    end

    if !params[:sort].nil? && params[:sort] == "LR"
      @articles = @articles.sort_by { |article|
        if article.liked_by.nil?
          0
        else
          article.liked_by.split(",").count
        end
      }.reverse
    elsif !params[:sort].nil? && params[:sort] == "C"
      @articles = @articles.sort_by { |article| Comment.where(article_id: article.id).count }
    elsif !params[:sort].nil? && params[:sort] == "CR"
      @articles = @articles.sort_by { |article| Comment.where(article_id: article.id).count }.reverse
    else
      @articles = @articles.sort_by { |article|
        if article.liked_by.nil?
          0
        else
          article.liked_by.split(",").count
        end
      }
    end

    @best_comments = Comment.where(:created_at => Time.now.prev_day(7)...Time.now).where.not(liked_by: nil).limit(3)
    @best_articles = Article.where(:created_at => Time.now.prev_day(7)...Time.now).sort_by {
      |article| Comment.where(article_id: article.id).count
    }.first 3

  end

  def show
    @article = Article.find_by id: params[:id]
    @article_creator = User.find_by id: @article.user_id
    @comments = Comment.where(article_id: @article.id)
    @comment = Comment.new
  end

  def edit
    @article = Article.find_by id: params[:id]
    if @current_user.id != @article.user_id
      render root
    end
  end

  def destroy
    @article = Article.find_by id: params[:id]
    @article.destroy
    redirect_to articles_path
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new article_params
    @article.user_id = @current_user.id
    @article.save!
    redirect_to articles_path
  end

  def update
    if @article.update article_params
      redirect_to article_path
    else
      render :edit
    end
  end

  def like
    @article = Article.find_by id: params[:id]
    if @article.liked_by.nil?
      @article.liked_by = @current_user.to_s + ","
    elsif @article.liked_by.include?(@current_user.id.to_s)
      @article.liked_by = @article.liked_by.chomp(@current_user.id.to_s + ",")
    elsif !@article.liked_by.include?(@current_user.id.to_s)
      @article.liked_by += @current_user.id.to_s + ","
    end
    @article.save!
    redirect_to article_path
  end

  private

  def find_article
    @article = Article.find_by id: params[:id]
  end

  def article_params
    params.require(:article).permit(:content, :body, :category, :title)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def edit
    @comment = Comment.find_by id: params[:id]
    if @current_user.id != @comment.user_id
      render root
    end
  end

  def update
    if @comment.update comment_params
      redirect_to article_path
    else
      render :edit
    end
  end

  def like
    @article = Article.find_by id: params[:article_id]
    @comment = Comment.find_by id: params[:comment_id]
    if @comment.liked_by.nil?
      @comment.liked_by = @current_user.to_s + ","
    elsif @comment.liked_by.include?(@current_user.id.to_s)
      @comment.liked_by = @article.liked_by.chomp(@current_user.id.to_s + ",")
    elsif !@comment.liked_by.include?(@current_user.id.to_s)
      @comment.liked_by += @current_user.id.to_s + ","
    end
    @comment.save!
    redirect_to article_path
  end

  def destroy
    @comment = Comment.find_by id: params[:id]
    @comment.destroy
    redirect_to article_comments_path
  end

  def create
    @article = Article.find_by id: params[:article_id]
    @comment = Comment.new comment_params
    @comment.user_id = current_user.id
    @comment.article_id = @article.id
    @comment.save!
    redirect_to "/articles/#{params[:article_id]}/comments"
  end

  def new
    @comment = Comment.new
  end

  private

  def comment_params
    params.require(:comment).permit(:liked_by, :content)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    "/user/#{current_user.id}/edit"
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def edit
    @user = User.find_by id: params[:id]
    if @user.id == current_user.id
    else
      redirect_to root_path
    end
  end

  def show
    @user = User.find_by id: params[:id]
    @articles = Article.where user_id: @user.id
  end

  def update
    if @current_user.update user_params
      redirect_to "/user/#{(User.find_by id: current_user.id).id}"
    else
      render :edit
    end
  end

  def like
    if !@current_user.favourite_users.nil? && @current_user.favourite_users.include?(params[:id].to_str)
      @current_user.favourite_users = @current_user.favourite_users.chomp(params[:id].to_str + ",")
    elsif @current_user.favourite_users.nil?
      @current_user.favourite_users = params[:id].to_str + ","
    else
      @current_user.favourite_users += params[:id].to_str + ","
    end
    @current_user.save
    redirect_to user_path
  end

  private


  def user_params
    params.require(:user).permit(:description, :avatar, :username)
  end
end

app/controllers/youtube_controller.rb
class YoutubeController < ApplicationController
  def show
    @youtube = Youtube.new(id: params[:id])
    render json: {
      sgid: @youtube.attachable_sgid,
      content: render_to_string(partial: "youtubes/thumbnail", locals: { youtube: @youtube }, formats: [:html])
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/articles/_form.html.erb
<div class="col-8 border rounded">
  <%= form_with model: @article do |form| %>
    <%= form.select :category, [ ["История", "HS"], ["Альтернативная история", "AH"], ["Аналитика", "AN"] ], class: "form-check form-check-input form-check-label" %>

    <%= form.text_field :title, placeholder: "Название статьи", class: "form-control mb-3 mt-3" %>

    <%= form.rich_text_area :content, class: "mb-3 mt-3 trix-content" %>

    <%= form.submit "Сохранить изменения", class: "btn btn-success btn-lg" %>
  <% end %>
</div>

app/views/articles/edit.html.erb
<div class="row mt-3 justify-content-center flex-nowrap">
  <%= render "form" %>
</div>

app/views/articles/index.html.erb
<div class="row mt-3 justify-content-center flex-nowrap">
  <div class="col-6 border rounded">
    <div class="mb-3 mt-3">
      <%= form_with url: "/", method: :get do |form| %>
        <%= form.select :tag, [ ["История", "HS"], ["Все", "AL"], ["Альтернативная история", "AH"], ["Аналитика", "AN"], ["Любимые авторы", "FA"] ]  %>

        <%= form.select :time, [ ["День", "D"], ["Неделя", "W"], ["Месяц", "M"], ["Год", "Y"], ["За всё время", "A"] ] %>

        <%= form.select :sort, [ ["Популярные", "L"], ["Обсуждаемые", "C"], ["Непопулярные", "LR"], ["Необсуждаемые", "CR"] ] %>

        <%= form.submit "Отсортировать" %>
      <% end %>
    </div>

    <% @articles.each do |article| %>
      <article class="card mt-3 mb-3">
        <div class="card-body">
          <span class="fs-2 fw-bold"><%= link_to article.title, "/articles/#{article.id}" %></span>

          <section class="card-text">
            <p class="my-2">
              <%= article.content.to_plain_text.truncate(200) %>
            </p>
          </section>

          <div class="mb-2">
            <% article_creator = User.find_by id: article.user_id %>
            <% if article_creator.username.nil? %>
              <%= article_creator.email.split("@").first %>
            <% else %>
              <%= article_creator.username %>
            <% end %>
          </div>

          <% if user_signed_in? && article_creator.id == current_user.id%>
            <%= link_to "Редактировать", "/articles/#{article.id}/edit", class: "btn btn-sm btn-primary" %>
          <% end %>
        </div>
      </article>
    <% end %>
  </div>
  <div class="col-2 border rounded">
    <%= render "layouts/sidebar" %>
  </div>
</div>

app/views/articles/new.html.erb
<div class="row mt-3 justify-content-center flex-nowrap">
  <%= render "form" %>
</div>

app/views/articles/show.html.erb
<div class="row mt-3 justify-content-center flex-nowrap">
  <div class="col-8 border rounded">
    <article class="card mt-3 mb-3">
      <div class="card-body">
        <div class="text-end">
          <% if user_signed_in? && @current_user.id != @article.user_id && (@article.liked_by.nil? || !@article.liked_by.include?(@current_user.id.to_s)) %>
            <%= link_to((image_tag "heart_empty.png", width: 30, height: 30), "/like_article/#{@article.id}", class: "mt-3") %>
          <% elsif user_signed_in? && @current_user.id != @article.user_id && @article.liked_by.include?(@current_user.id.to_s)%>
            <%= link_to((image_tag "heart_full.png", width: 30, height: 30), "/like_article/#{@article.id}", class: "mt-3") %>
          <% end %>
        </div>

        <span class="fs-2"><%= @article.title %></span>

        <section class="card-text">
          <p class="my-2 trix-content">
            <%= @article.content %>
          </p>
        </section>

        <div class="mb-2">
          <% if @article_creator.username.nil? %>
            <%= link_to @article_creator.email.split("@").first, "/user/#{@article_creator.id}" %>
          <% else %>
            <%= link_to @article_creator.username, "/user/#{@article_creator.id}" %>
          <% end %>
        </div>
        <% if user_signed_in? && @article_creator.id == current_user.id%>
          <%= link_to "Редактировать", edit_article_path, class: "btn btn-sm btn-primary" %>
        <% end %>
        <% if user_signed_in? && @article_creator.id == current_user.id%>
          <%= link_to "Удалить", "/articles/#{@article.id}", data: {turbo_method: :delete}, class: "btn btn-sm btn-danger" %>
        <% end %>
      </div>
    </article>
  </div>
</div>


<div class="row mt-3 justify-content-center flex-nowrap">
  <div class="col-8 border rounded">
    <span class="mt-3 fs-2"> Написать комментарий:</span>
    <article class="card mt-3 mb-3">
      <%= form_with model: [@article, @comment] do |form| %>
        <%= form.rich_text_area :content, class: "mb-3 mt-3 trix-content" %>

        <%= form.submit "Сохранить изменения", class: "btn btn-success btn-lg mb-2" %>
      <% end %>
    </article>
  </div>
</div>


<div class="row mt-3 justify-content-center flex-nowrap">
  <div class="col-8 border rounded">
    <% @comments.each do |comment| %>
      <article class="card mt-3 mb-3">

        <div class="text-end">
          <% if user_signed_in? && @current_user.id != comment.user_id && (comment.liked_by.nil? || !comment.liked_by.include?(@current_user.id.to_s)) %>
            <%= link_to((image_tag "heart_empty.png", width: 30, height: 30), "/like_comment/#{comment.id}", class: "mt-3") %>
          <% elsif user_signed_in? && @current_user.id != comment.user_id && comment.liked_by.include?(@current_user.id.to_s)%>
            <%= link_to((image_tag "heart_full.png", width: 30, height: 30), "/like_comment/#{comment.id}", class: "mt-3") %>
          <% end %>
        </div>

        <% comment_creator = User.find_by id: comment.user_id %>

        <div class="mb-2">
          <% if comment_creator.username.nil? %>
            <%= link_to comment_creator.email.split("@").first, "/user/#{comment_creator.id}" %>
          <% else %>
            <%= link_to comment_creator.username, "/user/#{comment_creator.id}" %>
          <% end %>
        </div>

        <section class="card-text">
          <p class="my-2 trix-content">
            <%= comment.content %>
          </p>
        </section>

        <div>
          <% if user_signed_in? && comment_creator.id == current_user.id%>
            <%= link_to "Редактировать", "/comment/#{comment.id}/edit", class: "btn btn-sm btn-primary mb-2" %>
          <% end %>
          <% if user_signed_in? && comment_creator.id == current_user.id%>
            <%= link_to "Удалить", "/articles/#{comment.id}", data: {turbo_method: :delete}, class: "btn btn-sm btn-danger" %>
          <% end %>
        </div>
      </article>
    <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<div class="col-8 border rounded">
  <%= form_with model: @comment do |form| %>
    <%= form.rich_text_area :content, class: "mb-3 mt-3 trix-content" %>

    <%= form.submit "Сохранить изменения", class: "btn btn-success btn-lg" %>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
      <%= image_tag "anchor.png" %>
      <span class="text-light fw-bold">Fleets Of All Time</span>
    </a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        </li>
      </ul>
      <ul class="navbar-nav">
        <% if current_user %>
          <% if @current_user.username.nil? %>
            <%= puts @current_user.email %>
            <%= puts @current_user.id %>
            <li class="nav-item"> <%= link_to @current_user.email.split("@").first, "/user/#{@current_user.id}", class: "nav-link link-light link-underline-opacity-0" %></li>
          <% else %>
            <li class="nav-item"> <%= link_to @current_user.username, "/user/#{@current_user.id}", class: "nav-link link-light link-underline-opacity-0" %></li>
          <% end %>
          <li class="nav-item"> <%= button_to "Выйти", destroy_user_session_path, method: :delete, class: "btn btn-small btn-light mx-2" %></li>
        <% else %>
          <li class="nav-item"> <%= link_to "Зарегистрироваться", new_user_registration_path, class: "btn btn-small btn-light mx-2"  %></li>
          <li class="nav-item"> <%= link_to "Войти", new_user_session_path, class: "btn btn-small btn-light mx-2"  %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<% pic_number = rand(8) %>
<% case pic_number %>
<% when 1 %>
  <%= image_tag "gorshkov.png", class: "mx-auto d-flex p-2 bd-highlight rounded" %>
<% when 2 %>
  <%= image_tag "1959_Ленин.jpg", class: "mx-auto d-flex p-2 bd-highlight rounded" %>
<% when 3 %>
  <%= image_tag "2023-09-10_17-00-57.png", class: "mx-auto d-flex p-2 bd-highlight rounded" %>
<% when 4 %>
  <%= image_tag "4036.jpg", class: "mx-auto d-flex p-2 bd-highlight rounded" %>
<% when 5 %>
  <%= image_tag "00088046.jpg", class: "mx-auto d-flex p-2 bd-highlight rounded" %>
<% when 6 %>
  <%= image_tag "iowa.png", class: "mx-auto d-flex p-2 bd-highlight rounded" %>
<% when 7 %>
  <%= image_tag "ri.jpg", class: "mx-auto d-flex p-2 bd-highlight rounded" %>
<% when 8 %>
  <%= image_tag "scale_1200 (1).jpg", class: "mx-auto d-flex p-2 bd-highlight rounded" %>
<% else %>
  <%= image_tag "конт.jpg", class: "mx-auto d-flex p-2 bd-highlight rounded" %>
<% end %>

<nav class="navbar navbar-dark bg-primary justify-content-center">
  <a class="nav-link link-light active me-3 fw-bold" href="/?tag=HS">История</a>
  <a class="nav-link link-light active me-3 fw-bold" href="/">Главная</a>
  <a class="nav-link link-light active me-3 fw-bold" href="/?tag=AH">Альтернативная история</a>
  <a class="nav-link link-light active me-3 fw-bold" href="/?tag=AN">Аналитика</a>
  <% if user_signed_in? %>
    <a class="nav-link link-light active me-3 fw-bold" href="/?tag=FA">Любимые авторы</a>
  <% end %>
</nav>

app/views/layouts/_sidebar.html.erb
<div class="mt-3"> Обсуждаемое за неделю:
  <% @best_articles.each do |article| %>
    <article class="card mt-3 mb-3">
      <div class="card-body">
        <span class="fw-bold"><%= link_to article.title, "/articles/#{article.id}" %></span>
      </div>
    </article>
  <% end %>
</div>

<div> Самые популярные комментарии за неделю:
  <% @best_comments.each do |comment| %>
    <article class="card mt-3 mb-3">
      <div class="card-body">
        <%=link_to comment.content.to_plain_text.truncate(30), article_comment_path %>
      </div>
    </article>
  <% end %>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AnotherBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>

app/views/user/edit.html.erb
<div class="row mt-3 justify-content-center flex-nowrap">
  <div class="col-8 border rounded">
    <%= form_with model: @user do |form| %>
      <div class="mt-3 mb-3">
        <%= form.label :avatar %>
        <%= form.file_field :avatar %>
      </div>
      <div class="mt-3 mb-3">
        <% if @user.username.nil? %>
          <%= form.text_field :username, placeholder: @user.email.split("@").first %>
        <% else %>
          <%= form.text_field :username, placeholder: @user.username %>
        <% end %>
      </div>

      <div class="mb-3">
        <% if @user.description.nil? %>
          <%= form.text_area :description, placeholder: "Расскажите о себе", class: "form-control" %>
        <% else %>
          <%= form.text_area :description, placeholder: @user.description, class: "form-control" %>
        <% end %>
      </div>

      <div class="text-center mb-3">
        <%= form.submit "Сохранить изменения", class: "btn btn-success btn-lg" %>
      </div>

    <% end %>
  </div>
</div>

app/views/user/show.html.erb
<div class="row mt-3 justify-content-center flex-nowrap">
  <div class="col-8 border rounded">
    <div class="justify-content-end">
    <% if @user.id == current_user.id %>
      <%= link_to "Редактировать профиль", "/user/#{current_user.id}/edit", class: "btn btn-primary btn-sm mt-3 mb-3"%>
    <% end %>
    <% if !@current_user.favourite_users.nil? && user_signed_in? && @user.id != current_user.id && @current_user.favourite_users.include?(@user.id.to_s) %>
      <%= link_to((image_tag "heart_full.png", width: 30, height: 30), "/like_user/#{@user.id}", class: "mt-3") %>
    <% elsif (@current_user.favourite_users.nil? && @user.id != current_user.id) || (user_signed_in? && @user.id != current_user.id && !@current_user.favourite_users.include?(@user.id.to_s)) %>
      <%= link_to((image_tag "heart_empty.png", width: 30, height: 30), "/like_user/#{@user.id}", class: "mt-3") %>
    <% end %>
    </div>

    <div>
    <% if @user.avatar.nil? %>
      <%= image_tag "placeholder.jpg", width: 200, height: 200, class: "rounded-circle me-4" %>
    <% else %>
      <%= image_tag @user.avatar, width: 200, height: 200, class: "rounded-circle me-4" %>
    <% end %>
    <% #begin %>
        <% # image_tag @user.avatar, width: 200, height: 200, class: "rounded-circle me-4" %>
    <% # rescue %>
        <% # image_tag "placeholder.jpg", width: 200, height: 200, class: "rounded-circle me-4" %>
    <% # end %>
      <span class="fs-1 fw-bold">
        <% if @user.username.nil? %>
          <%= current_user.email.split("@").first %>
        <% else %>
          <%= @user.username %>
        <% end %>
      </span>
    </div>

    <div>
      <% unless @user.description.nil? %>
        <div class="card mt-3">
          <%= @user.description %>
        </div>
      <% end %>
    </div>

    <div class="text-center">
      <% if @user.id == current_user.id %>
        <%= link_to "Создать статью", new_article_path, class: "btn btn-success btn-lg mt-3 mb-3"%>
      <% end %>
    </div>

    <div class="mb-5">
      <% if @articles.count == 0%>
        <span class="text-center fs-2 mt-3">Данный пользователь ещё не опубликовал ни одной статьи</span>
      <% else %>
        <% @articles.each do |article| %>
          <article class="card mt-3 mb-3">
            <div class="card-body">
              <span class="fs-2 fw-bold"><%= link_to article.title, "/articles/#{article.id}" %></span>

              <section class="card-text">
                <p class="my-2 trix-content">
                  <%= article.content.to_plain_text.truncate(70) %>
                </p>
              </section>
              <% if @user.id == current_user.id%>
                <%= link_to "Редактировать", "/", class: "btn btn-sm btn-primary" %>
              <% end %>
            </div>
          </article>
        <% end %>
      <% end %>
    </div>
  </div>
</div>